name: Deploy document

on:
  push:
    branches:
      - main
    paths:
      - 'source/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
    group: deploy-document-${{ github.ref_name }}
    cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v5

        - name: Build the document
          run: |
            uv run make clean html
        
        - name: Check environment
          id: check-env
          run: |
            if [ -n "$ACT" ]; then
              echo "is_act=true" >> $GITHUB_OUTPUT
            else
              echo "is_act=false" >> $GITHUB_OUTPUT
            fi
        
        # Actionsに用意されているpagesのアクションを使ってbuild/html以下をPagesで公開
        - name: Upload artifact
          if: steps.check-env.outputs.is_act != 'true'
          uses: actions/upload-pages-artifact@v3
          with:
            # Upload entire repository
            path: 'build/html'
        - name: Deploy to GitHub Pages
          if: steps.check-env.outputs.is_act != 'true'
          id: deployment
          uses: actions/deploy-pages@v4